
version: '3.8'

services:
  milky-way-app:
    build: 
      context: .
      dockerfile: Dockerfile.txt
    container_name: milkyway_app
    restart: always
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=8080
    networks:
      - mw-network
    deploy:
      resources:
        limits:
          memory: 768M

  milky-way-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: milkyway_tunnel
    restart: always
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
    depends_on:
      - milky-way-app
    networks:
      - mw-network

networks:
  mw-network:
    driver: bridge
